### PR TITLE
Removing NIL constant + retabbing file

### PR DESCRIPTION
**Pull request by rapofran**
Removing NIL constant for ruby 2.4

### CODE REVIEW

**Comment by aberant** [comment]
Thanks!  I'll take a look at this tomorrow.

**Comment by aberant** [comment]
Thanks so much.  I've updated the README to give you credit.

**Comment by munshkr** [comment]
@aberant thank you for merging this! We're actually using your gem for [a music patterns library in Ruby for livecoding](https://github.com/xi-livecode/xi/), and those Ruby warnings were kind of annoying :)
Would you be so kind enough to release a new patch version with this fix?

**Comment by aberant** [comment]
Awesome!  I've got it in my queue.  I _might_ have time to do it today, but otherwise I'll get to it asap.  

Please let me know if there's anything else annoying or nice to have as your develop your library.  Also, if you need a tester for your software, let me know.  

I gave credit to rapofran, but is there a group name that would be better to give credit to?

**Comment by munshkr** [comment]
Thanks so much! Take your time, whenever you're available.

>Please let me know if there's anything else annoying or nice to have as your develop your library. Also, if you need a tester for your software, let me know.

Sure, I'll let you know if you're interested. So far the osc part has been working great :)

> I gave credit to rapofran, but is there a group name that would be better to give credit to?

It's fine by me as it is now.

**Comment by aberant** [comment]
Turned out to be easier than I thought despite not touching this for a while.  Please let me know if there are any issues with 1.1.2

**Comment by munshkr** [comment]
Awesome, thanks again!

**Pull request merged**
